version: '3.9'
services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - MONGODB_URI=MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo_db
    restart: always

  mongo_db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_db:/data/db
    restart: always

volumes:
  mongo_db: {}
